## Import librares

In [30]:
import pandas as pd

### Import Data from data folder
- Set Date as the Index and parse_dates=True to convert to datetime
- Our dataset contains dates in the "DD/MM/YYYY" format instead of the default "MM/DD/YYYY" used in some systems

In [36]:
df = pd.read_csv("../data/airmiles.csv",index_col="Date",parse_dates=True,dayfirst=True)
df.head()

            airmiles
Date
1996-01-01  30983174
1996-02-01  32147663
1996-03-01  38342975
1996-04-01  35969113
1996-05-01  36474391

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 113 entries, 1996-01-01 to 2005-01-05
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   airmiles  113 non-null    int64
dtypes: int64(1)
memory usage: 1.8 KB

### There is no frequency at df.index so we used asfreq('MS') as we are having monthly data

In [42]:
df = df.asfreq('MS')
df.index

DatetimeIndex(['1996-01-01', '1996-02-01', '1996-03-01', '1996-04-01',
               '1996-05-01', '1996-06-01', '1996-07-01', '1996-08-01',
               '1996-09-01', '1996-10-01',
               ...
               '2004-08-01', '2004-09-01', '2004-10-01', '2004-11-01',
               '2004-12-01', '2005-01-01', '2005-02-01', '2005-03-01',
               '2005-04-01', '2005-05-01'],
              dtype='datetime64[ns]', name='Date', length=113, freq='MS')

### Check for nan values

In [43]:
df.isna().sum().sum()

np.int64(0)

In [44]:
df.shape

(113, 1)

### Renaming Dependent Variable(airmiles) to y

In [45]:
df.rename(columns={"airmiles":"y"},inplace=True)

In [46]:
df.head()

                   y
Date
1996-01-01  30983174
1996-02-01  32147663
1996-03-01  38342975
1996-04-01  35969113
1996-05-01  36474391

In [47]:
import os
df.to_csv(os.path.join("..","data","preprocessedData.csv"),index=True)